export enum ActionType {
  LOAD_TODO_REQUEST = "LOAD_TODO_REQUEST",
  LOAD_TODO_SUCCESS = "LOAD_TODO_SUCCESS",
  LOAD_TODO_FAILURE = "LOAD_TODO_FAILURE",
  ADD_TODO_REQUEST = "ADD_TODO_REQUEST",
  ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS",
  ADD_TODO_FAILURE = "ADD_TODO_FAILURE",
  DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST",
  DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE",
  UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST",
  UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE",
}
